config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :books
  resources :users do
    member do
      post :follow
      delete :unfollow
    end
  end
    # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :books_users

end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :books, join_table: :books_users

  has_many :followed_relationships, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, foreign_key: :follower_id, class_name: "Follower"

  has_many :follower_relationships, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower


  validates :email, presence: true, uniqueness: true
  validates :nickname, presence: true, uniqueness: true



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def read_books
    books.where('books_users.read = ?', true)
  end

  def follow(other_user)
    followed_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    followed_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    followed_relationships.exists?(followed_id: other_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nickname])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'google/apis/books_v1'

  def index
    @query = params[:q]
    @genre = params[:genre]
    @sort_by = params[:sort_by]

    books_api = Google::Apis::BooksV1::BooksService.new
    books_api.key = ENV['GOOGLE_BOOKS_KEY']

    # Build the query parameters based on the selected genre and sort_by
    query_params = @query.present? ? { q: @query } : { q: "averageRating:>4" }
    query_params[:subject] = @genre if @genre.present?
    query_params[:order_by] = @sort_by if @sort_by.present?

    # Query the Books API
    @books = books_api.list_volumes(query_params, max_results: 30)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @most_followed = User.all.sort_by { |user| -user.followers.count }.take(3)
    @most_read = User.all.sort_by { |user| -user.books.count }.take(3)


  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to users_path
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(@user)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :nickname, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<div class="container p-4" style='margin: 30px auto'>


<div class="d-flex justify-content-center my-4">
  <%= form_with(url: books_path, method: :get) do |form| %>
    <div class="input-group">
      <%= form.text_field :q, value: params[:q], placeholder: 'Enter a book title, author, or keyword', class: 'form-control rounded-0 border-end-0' %>
      <%= form.select :genre, ['Fiction', 'Nonfiction', 'Mystery', 'Romance', 'Thriller', 'Science Fiction'], { prompt: 'Filter by Genre' }, { class: 'form-select rounded-0 border-start-0' } %>
      <button class="btn btn-dark rounded-0" type="submit" style="background-color: #00b4db">Search</button>
    </div>
  <% end %>
</div>


<% if @books.present? %>
  <div class="row m-auto justify-content-center">
    <% @books.items.each do |book| %>
      <div class="col-md-2 mb-4">
        <div class="card book-card">
          <div class="card-img-container">
            <img src="<%= book.volume_info.image_links.thumbnail %>" class="card-img-top" style="height: 100%; object-fit: cover;">
            <div class="card-img-overlay">
              <h5 class="card-title mb-0"><%= book.volume_info.title %></h5>
              <p class="card-text mb-0"><%= book.volume_info.authors.to_s.delete('["]')  %></p>
            </div>
          </div>
          <div class="card-details">
            <div class="card-details-inner">
              <p class="card-text mb-3"><%= book.volume_info.title %></p>
              <%= link_to 'Details', book_path(book), class: 'btn btn-primary mb-3' %>
              <p class="card-text"><small class="text-muted"><%= book.volume_info.authors.to_s.delete('["]')  %></small></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No results found</p>
<% end %>




</div>

app/views/books/show.html.erb
<div class="container">
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="<%= @book.volume_info.image_links.thumbnail %>" class="img-fluid rounded-start">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @book.volume_info.title %></h5>
        <p class="card-text"><%= @book.volume_info.authors.to_s.delete('["]')  %></p>
        <p class="card-text"><%= @book.volume_info.description %></p>
        <p class="card-text"><small class="text-muted"><%= @book.volume_info.published_date %></small></p>
      </div>
    </div>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookMatcher</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>

    <%= render "shared/navbar" %>

    <%= render "shared/flashes" %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="home-body">
  <div class="area" >
    <header class="py-5 d-flex align-items-center justify-content-center" style='height: 100vh;'>
      <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
          <div class="col-lg-9 col-xl-7 col-xxl-7 text-center">
            <div class="my-5 text-center">
              <h1 class="display-5 fw-bolder text-white mb-2">The Ultimate Reading Experience</h1>
              <p class="lead fw-normal text-white-50 mb-4">Get personalized reading recommendations, track your progress, and connect with a community of book lovers. Earn badges and climb the leaderboard as you read your way to the top.</p>
              <div class="justify-content-sm-center justify-content-xl-start text-center">
              <% if user_signed_in? %>
               <%= link_to 'Get Started', books_path, class: 'btn btn-dark btn-lg' %>
              <% else %>
                <%= link_to 'Get Started', new_user_registration_path, class: 'btn btn-dark btn-lg' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>

    <ul class="circles" style="pointer-events:none;">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark nav-masthead justify-content-center">
                <div class="container px-5">
                    <%= link_to 'BookMatch', root_path, class: 'navbar-brand asthead-brand', style: 'font-weight: bold ' %>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item"><%= link_to 'Feed', '#', class: 'nav-link' %></li>
                            <li class="nav-item"><%= link_to 'Books', books_path, class: 'nav-link' %></li>
                            <li class="nav-item"><%= link_to 'Readers', users_path, class: 'nav-link' %></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">User</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                <li><a class="dropdown-item" href="blog-home.html">My Profile</a></li>
                                    <li><a class="dropdown-item" href="blog-home.html">My Books</a></li>
                                    <li><a class="dropdown-item" href="blog-post.html">My Follows</a></li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </nav>

app/views/users/index.html.erb
<div class="container">
<h1 class='mx-auto mt-2 text-center'>Most Followed: </h1>

<div class="row m-auto justify-content-center">
  <% @most_followed.each do |user| %>
    <div class="col-md-4 col-sm-12">
      <div class="card user-card m-4">
        <div class="card-block">
          <div class="user-image">
            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" class="img-radius" alt="User-Profile-Image">
          </div>
          <h6 class="f-w-600 m-t-25 m-b-10"><%= user.nickname %></h6>
          <hr>
          <div class="bg-c-blue counter-block m-t-10 p-20">
            <div class="row">
              <div class="col-6">
                 <i class="fa fa-users"></i> Followers
                <p><%= user.followers.count %></p>
              </div>
              <div class="col-6">
                <i class="fa fa-book"></i> Books
                <p><%= user.books.count %></p>
              </div>
            </div>
          </div>
          <hr>
          <div class="row justify-content-center user-social-link">
            <div class="d-flex justify-content-center align-items-center">
            <%= link_to 'Details', user_path(user), class: 'btn btn-outline-primary m-2' %>
            <% unless current_user.following?(user) %>
                <%= form_with url: follow_user_path(user), class: 'm-0', method: :post do %>
                  <%= submit_tag "Follow", class: "btn btn-primary" %>
                <% end %>
            <% end %>
            <% if current_user.following?(user) %>
                <%= form_with url: unfollow_user_path(user), method: :delete do %>
                  <%= submit_tag "Unfollow", class: "btn btn-outline-primary m-2" %>
                <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>



<h1 class='mx-auto mt-2 text-center'>Quickest Readers: </h1>
<div class="row m-auto justify-content-center">
  <% @most_followed.each do |user| %>
    <div class="col-md-4 col-sm-12">
      <div class="card user-card m-4">
        <div class="card-block">
          <div class="user-image">
            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" class="img-radius" alt="User-Profile-Image">
          </div>
          <h6 class="f-w-600 m-t-25 m-b-10"><%= user.nickname %></h6>
          <hr>
          <div class="bg-c-blue counter-block m-t-10 p-20">
            <div class="row">
              <div class="col-6">
                 <i class="fa fa-users"></i> Followers
                <p><%= user.followers.count %></p>
              </div>
              <div class="col-6">
                <i class="fa fa-book"></i> Books
                <p><%= user.books.count %></p>
              </div>
            </div>
          </div>
          <hr>
          <div class="row justify-content-center user-social-link">
            <div class="d-flex justify-content-center align-items-center">
            <%= link_to 'Details', user_path(user), class: 'btn btn-outline-primary m-2' %>
            <% unless current_user.following?(user) %>
                <%= form_with url: follow_user_path(user), class: 'm-0', method: :post do %>
                  <%= submit_tag "Follow", class: "btn btn-primary" %>
                <% end %>
            <% end %>
            <% if current_user.following?(user) %>
                <%= form_with url: unfollow_user_path(user), method: :delete do %>
                  <%= submit_tag "Unfollow", class: "btn btn-outline-primary m-2" %>
                <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<h1>Favorite by Genre: </h1>

</div>